/* 
 * File:   enumns.h
 * Author: Justin
 *
 * Created on February 6, 2016, 12:28 PM
 */
//sublties in the code
//BALLSFULL gets updated using timer3 only during SHOOTGOALS, and by LOADBALLS
//timer 2 used for ultra sonic
//timer 3 used for time shooting goals

#ifndef ENUMS_H
#define	ENUMS_H

//events
enum {DISPENSERLIGHTDETECTED, DISPENSERLIGHTTHRESHOLDMET, BINLIGHTDETECTED, BINLIGHTNOTDETECTED, BINLIGHTTHRESHOLDMET, ONESONICSENSORTHRESHOLDMET, TWOSONICSENSORTHRESHOLDMET, TIMER1MET, BUTTONPRESSED, BALLSFULL};

//states
enum {WAITFORBUTTON, TURNFINDIR, FACEDISPENSER, DRIVETOCORNERQUICK, DRIVEINTOCORNER, LOADBALLS, DRIVETOMIDDLE, FACEBIN, BACKUPTOSHOOT, SHOOTGOALS};

//event status variables
enum {SHOOTTIME};

//manipulator commands
enum {CLEAR, UPDATE, REQUEST, INCREMENT};
#endif	/* ENUMS_H */

