/* 
 * File:   enumns.h
 * Author: Justin
 *
 * Created on February 6, 2016, 12:28 PM
 */

#ifndef ENUMS_H
#define	ENUMS_H

//events
enum {DISPENSERLIGHTDETECTED, DISPENSERLIGHTTHRESHOLDMET, BINLIGHTDETECTED, BINLIGHTTHRESHOLDMET, CORNERSENSORTHRESHOLDMET, CORNERSENSORSEQUIVALENT, TIMEREVENT, BUTTONPRESSED, BALLSLOADED};

//states
enum {WAITFORBUTTON, TURNFINDDISPENSER, FACEDISPENSER, DRIVETOCORNER, LOADDISPENSER, DRIVETOMIDDLE, TURNFINDBINSENSOR, FACEBIN, BACKUPTOSHOOT, SHOOTGOALS};

#endif	/* ENUMS_H */

